Server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/countries?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC& cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    password: 111www111
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      order_insets: true
      ddl-auto: update
    show-sql: true

